[package]
name = "gearbot"
version = "0.1.0"
authors = ["AEnterprise <aenterprise@aenterprise.info>", "BlackHoleFox <blackholefoxdev@gmail.com>", "GearBot Contributors"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.5"
chrono = "0.4"
clap = { version = "2.33", default-features = false }
darkredis = "0.7"
ctrlc = { version = "3", features = ["termination"] }
dashmap = {version = "4.0.0-rc6", features=["serde"]}
sqlx =  { version = "0.4.0-beta.1", default-features = false, features = ["postgres", "json", "runtime-tokio", "macros", "migrate"] }
flexi_logger = { version = "0.15", default-features = false, features = ["colors", "specfile", "ziplogs"] }
futures-util = "0.3"
fluent-bundle = "0.12"
git-version = "0.3"
lazy_static = "1.4"
log = "0.4"
once_cell = "1.4"
prometheus = "0.8"
rand = "0.7"
regex = "1.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1"
tokio = { version = "0.2", default-features = false, features = ["macros", "sync", "rt-core"] }
toml = "0.5"
twilight = { git="https://github.com/twilight-rs/twilight", branch="trunk" }
url = "2.1"
unic-langid = { version = "0.9", features = ["macros", "serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
# TODO: Replace this with Hyper
warp = "0.2"

[profile.dev]
debug = 0

[profile.release]
lto = true