[package]
name = "gearbot_2"
version = "0.1.0"
authors = ["BlackHoleFox <blackholefoxdev@gmail.com>", "AEnterprise <aenterprise@aenterprise.info>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
git-version = "0.3"
tokio = "0.2"
twilight = { git = "https://github.com/twilight-rs/twilight.git" }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
flexi_logger = { version = "0.15", default_features = false, features = ["colors", "specfile", "ziplogs"] }
log = "0.4"
once_cell = "1.3"
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono", "json" ] }