[package]
name = "gearbot_2"
version = "0.1.0"
authors = ["BlackHoleFox <blackholefoxdev@gmail.com>", "AEnterprise <aenterprise@aenterprise.info>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.15"
git-version = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
tokio = "0.2"
twilight = { git = "https://github.com/twilight-rs/twilight.git" }