[package]
name = "gearbot"
version = "0.1.0"
authors = ["BlackHoleFox <blackholefoxdev@gmail.com>", "AEnterprise <aenterprise@aenterprise.info>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
flexi_logger = { version = "0.15", default_features = false, features = ["colors", "specfile", "ziplogs"] }
git-version = "0.3"
lazy_static = "1.4"
log = "0.4"
once_cell = "1.3"
rand = "0.7"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono", "json" ] }
tokio = { version = "0.2", default_features = false, features = ["macros", "sync", "rt-core"] }
toml = "0.5"
twilight = { git = "https://github.com/twilight-rs/twilight.git" }