[tokens]
discord = ""

[logging]
important_logs = "https://canary.discordapp.com/api/webhooks/id/token"
info_logs = "https://canary.discordapp.com/api/webhooks/id/token"

[database]
postgres="postgres://database?user=user&password=password&host=localhost"